# Generated by Django 2.0.3 on 2018-12-02 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0002_auto_20181128_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='group',
        ),
        migrations.RemoveField(
            model_name='address',
            name='person',
        ),
        migrations.AddField(
            model_name='person',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='phonebook.Address'),
        ),
    ]
